### ISSUE TITLE
`path.conf`should be a string not a file 

### ISSUE THREAD

**Issue by alperyeg** [Meta-optimization/L2L#19]
When starting the script a config file, `path.conf` is required which sets the path to the results. This should be a string, instead a config file. Additionally the path should be checked a directory should be added if the folder is missing.

**Comment by sdiazpier** [comment]
Yes I think this is a good idea, to remove the path.conf file and leave a string which has to be defined by the user before the execution.

**Comment by alperyeg** [comment]
With the experiment class this is issue can be closed or is discussion still needed?

**Comment by sdiazpier** [comment]
I think this can be closed now. the experiment class works well now.
