### ISSUE TITLE
Bug: install.sh uses pip. Modern linux versions have switched to pip3

### ISSUE THREAD

**Issue by w-klijn** [Meta-optimization/L2L#40]
The current versions of linux do not come with pip but pip3.
This means that out of the box newer linux users can not use the install script

Some intelligence needs to be added to the install.sh to catch this behavior.

**Comment by w-klijn** [comment]
pip3 does work to do the jube installation

**Comment by alperyeg** [comment]
What python version is installed per default on your system? For me python2 is not installed, so executing pip is using python3.

**Comment by brenthuisman** [comment]
This issue is a bit distro specific (what `pip` resolves to). `pip3` should always resolve to the Python3 version, so also in our Arbor documentation do we use `pip3` and `python3` everywhere.

**Comment by alperyeg** [comment]
Thanks, good to know. We should change it to pip3 then.

**Comment by alperyeg** [comment]
Was closed with PR #44
