### ISSUE TITLE
[Bug] Setup instruction relies on old pip versions.

### ISSUE THREAD

**Issue by brenthuisman** [Meta-optimization/L2L#42]
The commandline option `--process-dependency-links` was dropped in [pip v19](https://github.com/pypa/pip/issues/6162). What's the advised alternative?

I see a `install.sh` in the root, but that appears to be doing something unrelated. Or do I see that wrong?

**Comment by alperyeg** [comment]
Links to #41

**Comment by brenthuisman** [comment]
If I run `python3 setup.py install --user` instead indeed #41 pops up. If I remove the matplotlib dep from `requirements.txt`, il2l installs without errors!

**Comment by alperyeg** [comment]
Very good. We can leave the issue open at the moment, in case other people have the same problem.

**Comment by alperyeg** [comment]
Was fixed with latest PR
