### ISSUE TITLE
Improve the debug functionality

### ISSUE THREAD

**Issue by sdiazpier** [Meta-optimization/L2L#78]
A dedicated variable and functionality for debugging the output of the individuals has been added but it is in minimal state. Some polishing is needed.

**Comment by alperyeg** [comment]
#80 enabled debug output to be turned on.

**Comment by sdiazpier** [comment]
We need to make the debug functionality more user friendly and the Debug flag, which should be False by default, is still True by default. 
Errors should only be shown when there is an actual error to be reported, otherwise no output should be shown on screen.
